com.sun.management:type=DiagnosticCommand
com.sun.management:type=HotSpotDiagnostic
java.lang:name=CodeCacheManager,type=MemoryManager
java.lang:name=Code Cache,type=MemoryPool
java.lang:name=Compressed Class Space,type=MemoryPool
java.lang:name=G1 Eden Space,type=MemoryPool
java.lang:name=G1 Old Generation,type=GarbageCollector
java.lang:name=G1 Old Gen,type=MemoryPool
java.lang:name=G1 Survivor Space,type=MemoryPool
java.lang:name=G1 Young Generation,type=GarbageCollector
java.lang:name=Metaspace Manager,type=MemoryManager
java.lang:name=Metaspace,type=MemoryPool
java.lang:type=ClassLoading
java.lang:type=Compilation
java.lang:type=Memory
java.lang:type=OperatingSystem
java.lang:type=Runtime
java.lang:type=Threading
java.nio:name=direct,type=BufferPool
java.nio:name=mapped,type=BufferPool
java.util.logging:type=Logging
JMImplementation:type=MBeanServerDelegate
jmx4perl:type=Config
jolokia:type=Config
jolokia:type=Discovery
jolokia:type=ServerHandler

kafka.cluster:name=UnderReplicated,partition=0,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=10,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=11,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=12,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=14,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=1,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=2,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=4,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=5,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=6,topic=qaastor-1.s8,type=Partition
kafka.cluster:name=UnderReplicated,partition=8,topic=qaastor-1.s8,type=Partition

kafka.controller:name=ActiveControllerCount,type=KafkaController
kafka.controller:name=LeaderElectionRateAndTimeMs,type=ControllerStats
kafka.controller:name=OfflinePartitionsCount,type=KafkaController
kafka.controller:name=PreferredReplicaImbalanceCount,type=KafkaController
kafka.controller:name=UncleanLeaderElectionsPerSec,type=ControllerStats

kafka.coordinator:name=NumGroups,type=GroupMetadataManager
kafka.coordinator:name=NumOffsets,type=GroupMetadataManager

kafka.network:name=IdlePercent,networkProcessor=0,type=Processor
kafka.network:name=IdlePercent,networkProcessor=1,type=Processor
kafka.network:name=IdlePercent,networkProcessor=2,type=Processor
kafka.network:name=IdlePercent,networkProcessor=3,type=Processor
kafka.network:name=IdlePercent,networkProcessor=4,type=Processor
kafka.network:name=IdlePercent,networkProcessor=5,type=Processor
kafka.network:name=IdlePercent,networkProcessor=6,type=Processor
kafka.network:name=IdlePercent,networkProcessor=7,type=Processor
kafka.network:name=IdlePercent,networkProcessor=8,type=Processor
kafka.network:name=IdlePercent,networkProcessor=9,type=Processor
kafka.network:name=LocalTimeMs,request=ApiVersions,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=ControlledShutdown,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=DescribeGroups,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=FetchConsumer,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=FetchFollower,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=Fetch,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=GroupCoordinator,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=Heartbeat,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=JoinGroup,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=LeaderAndIsr,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=LeaveGroup,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=ListGroups,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=Metadata,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=OffsetCommit,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=OffsetFetch,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=Offsets,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=Produce,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=SaslHandshake,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=StopReplica,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=SyncGroup,type=RequestMetrics
kafka.network:name=LocalTimeMs,request=UpdateMetadata,type=RequestMetrics
kafka.network:name=NetworkProcessorAvgIdlePercent,type=SocketServer
kafka.network:name=RemoteTimeMs,request=ApiVersions,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=ControlledShutdown,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=DescribeGroups,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=FetchConsumer,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=FetchFollower,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=Fetch,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=GroupCoordinator,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=Heartbeat,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=JoinGroup,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=LeaderAndIsr,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=LeaveGroup,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=ListGroups,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=Metadata,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=OffsetCommit,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=OffsetFetch,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=Offsets,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=Produce,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=SaslHandshake,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=StopReplica,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=SyncGroup,type=RequestMetrics
kafka.network:name=RemoteTimeMs,request=UpdateMetadata,type=RequestMetrics
kafka.network:name=RequestQueueSize,type=RequestChannel
kafka.network:name=RequestQueueTimeMs,request=ApiVersions,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=ControlledShutdown,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=DescribeGroups,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=FetchConsumer,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=FetchFollower,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=Fetch,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=GroupCoordinator,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=Heartbeat,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=JoinGroup,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=LeaderAndIsr,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=LeaveGroup,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=ListGroups,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=Metadata,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=OffsetCommit,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=OffsetFetch,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=Offsets,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=Produce,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=SaslHandshake,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=StopReplica,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=SyncGroup,type=RequestMetrics
kafka.network:name=RequestQueueTimeMs,request=UpdateMetadata,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=ApiVersions,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=ControlledShutdown,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=DescribeGroups,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=FetchConsumer,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=FetchFollower,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=Fetch,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=GroupCoordinator,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=Heartbeat,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=JoinGroup,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=LeaderAndIsr,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=LeaveGroup,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=ListGroups,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=Metadata,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=OffsetCommit,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=OffsetFetch,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=Offsets,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=Produce,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=SaslHandshake,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=StopReplica,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=SyncGroup,type=RequestMetrics
kafka.network:name=RequestsPerSec,request=UpdateMetadata,type=RequestMetrics
kafka.network:name=ResponseQueueSize,processor=0,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=10,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=11,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=12,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=13,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=14,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=15,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=1,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=2,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=3,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=4,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=5,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=6,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=7,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=8,type=RequestChannel
kafka.network:name=ResponseQueueSize,processor=9,type=RequestChannel
kafka.network:name=ResponseQueueSize,type=RequestChannel
kafka.network:name=ResponseQueueTimeMs,request=ApiVersions,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=ControlledShutdown,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=DescribeGroups,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=FetchConsumer,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=FetchFollower,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=Fetch,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=GroupCoordinator,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=Heartbeat,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=JoinGroup,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=LeaderAndIsr,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=LeaveGroup,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=ListGroups,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=Metadata,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=OffsetCommit,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=OffsetFetch,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=Offsets,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=Produce,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=SaslHandshake,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=StopReplica,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=SyncGroup,type=RequestMetrics
kafka.network:name=ResponseQueueTimeMs,request=UpdateMetadata,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=ApiVersions,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=ControlledShutdown,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=DescribeGroups,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=FetchConsumer,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=FetchFollower,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=Fetch,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=GroupCoordinator,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=Heartbeat,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=JoinGroup,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=LeaderAndIsr,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=LeaveGroup,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=ListGroups,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=Metadata,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=OffsetCommit,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=OffsetFetch,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=Offsets,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=Produce,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=SaslHandshake,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=StopReplica,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=SyncGroup,type=RequestMetrics
kafka.network:name=ResponseSendTimeMs,request=UpdateMetadata,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=ApiVersions,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=ControlledShutdown,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=DescribeGroups,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=FetchConsumer,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=FetchFollower,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=Fetch,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=GroupCoordinator,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=Heartbeat,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=JoinGroup,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=LeaderAndIsr,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=LeaveGroup,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=ListGroups,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=Metadata,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=OffsetCommit,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=OffsetFetch,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=Offsets,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=Produce,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=SaslHandshake,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=StopReplica,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=SyncGroup,type=RequestMetrics
kafka.network:name=ThrottleTimeMs,request=UpdateMetadata,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=ApiVersions,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=ControlledShutdown,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=DescribeGroups,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=FetchConsumer,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=FetchFollower,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=Fetch,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=GroupCoordinator,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=Heartbeat,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=JoinGroup,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=LeaderAndIsr,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=LeaveGroup,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=ListGroups,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=Metadata,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=OffsetCommit,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=OffsetFetch,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=Offsets,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=Produce,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=SaslHandshake,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=StopReplica,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=SyncGroup,type=RequestMetrics
kafka.network:name=TotalTimeMs,request=UpdateMetadata,type=RequestMetrics

kafka.server:brokerHost=n5.s1,brokerPort=9093,clientId=ReplicaFetcherThread-0-5,name=BytesPerSec,type=FetcherStats
kafka.server:brokerHost=n5.s1,brokerPort=9093,clientId=ReplicaFetcherThread-0-5,name=RequestsPerSec,type=FetcherStats
kafka.server:brokerHost=n7.s1,brokerPort=9093,clientId=ReplicaFetcherThread-0-7,name=BytesPerSec,type=FetcherStats
kafka.server:brokerHost=n7.s1,brokerPort=9093,clientId=ReplicaFetcherThread-0-7,name=RequestsPerSec,type=FetcherStats
kafka.server:broker-id=5,fetcher-id=0,type=replica-fetcher-metrics
kafka.server:broker-id=7,fetcher-id=0,type=replica-fetcher-metrics
kafka.server:client-id=123-ABC,type=Fetch
kafka.server:client-id=123-ABC,type=Produce
kafka.server:clientId=ReplicaFetcherThread-0-5,name=ConsumerLag,partition=0,topic=qaastor-1.s8,type=FetcherLagMetrics
kafka.server:clientId=ReplicaFetcherThread-0-5,name=ConsumerLag,partition=10,topic=qaastor-1.s8,type=FetcherLagMetrics
kafka.server:clientId=ReplicaFetcherThread-0-5,name=ConsumerLag,partition=4,topic=qaastor-1.s8,type=FetcherLagMetrics
kafka.server:clientId=ReplicaFetcherThread-0-7,name=ConsumerLag,partition=12,topic=qaastor-1.s8,type=FetcherLagMetrics
kafka.server:clientId=ReplicaFetcherThread-0-7,name=ConsumerLag,partition=6,topic=qaastor-1.s8,type=FetcherLagMetrics
kafka.server:clientId=Replica,name=MaxLag,type=ReplicaFetcherManager
kafka.server:clientId=Replica,name=MinFetchRate,type=ReplicaFetcherManager
kafka.server:delayedOperation=Fetch,name=NumDelayedOperations,type=DelayedOperationPurgatory
kafka.server:delayedOperation=Fetch,name=PurgatorySize,type=DelayedOperationPurgatory
kafka.server:delayedOperation=Heartbeat,name=NumDelayedOperations,type=DelayedOperationPurgatory
kafka.server:delayedOperation=Heartbeat,name=PurgatorySize,type=DelayedOperationPurgatory
kafka.server:delayedOperation=Produce,name=NumDelayedOperations,type=DelayedOperationPurgatory
kafka.server:delayedOperation=Produce,name=PurgatorySize,type=DelayedOperationPurgatory
kafka.server:delayedOperation=Rebalance,name=NumDelayedOperations,type=DelayedOperationPurgatory
kafka.server:delayedOperation=Rebalance,name=PurgatorySize,type=DelayedOperationPurgatory
kafka.server:fetcherType=consumer,name=ExpiresPerSec,type=DelayedFetchMetrics
kafka.server:fetcherType=follower,name=ExpiresPerSec,type=DelayedFetchMetrics
kafka.server:id=6,type=app-info
kafka.server:name=BrokerState,type=KafkaServer
kafka.server:name=BytesInPerSec,topic=qaastor-1.s8,type=BrokerTopicMetrics
kafka.server:name=BytesInPerSec,type=BrokerTopicMetrics
kafka.server:name=BytesOutPerSec,topic=qaastor-1.s8,type=BrokerTopicMetrics
kafka.server:name=BytesOutPerSec,type=BrokerTopicMetrics
kafka.server:name=BytesRejectedPerSec,topic=qaastor-1.s8,type=BrokerTopicMetrics
kafka.server:name=BytesRejectedPerSec,type=BrokerTopicMetrics
kafka.server:name=FailedFetchRequestsPerSec,topic=qaastor-1.s8,type=BrokerTopicMetrics
kafka.server:name=FailedFetchRequestsPerSec,type=BrokerTopicMetrics
kafka.server:name=FailedProduceRequestsPerSec,topic=qaastor-1.s8,type=BrokerTopicMetrics
kafka.server:name=FailedProduceRequestsPerSec,type=BrokerTopicMetrics
kafka.server:name=IsrExpandsPerSec,type=ReplicaManager
kafka.server:name=IsrShrinksPerSec,type=ReplicaManager
kafka.server:name=LeaderCount,type=ReplicaManager
kafka.server:name=MessagesInPerSec,topic=qaastor-1.s8,type=BrokerTopicMetrics
kafka.server:name=MessagesInPerSec,type=BrokerTopicMetrics
kafka.server:name=PartitionCount,type=ReplicaManager
kafka.server:name=RequestHandlerAvgIdlePercent,type=KafkaRequestHandlerPool
kafka.server:name=TotalFetchRequestsPerSec,topic=qaastor-1.s8,type=BrokerTopicMetrics
kafka.server:name=TotalFetchRequestsPerSec,type=BrokerTopicMetrics
kafka.server:name=TotalProduceRequestsPerSec,topic=qaastor-1.s8,type=BrokerTopicMetrics
kafka.server:name=TotalProduceRequestsPerSec,type=BrokerTopicMetrics
kafka.server:name=UnderReplicatedPartitions,type=ReplicaManager
kafka.server:name=yammer-metrics-count,type=KafkaServer
kafka.server:name=ZooKeeperAuthFailuresPerSec,type=SessionExpireListener
kafka.server:name=ZooKeeperDisconnectsPerSec,type=SessionExpireListener
kafka.server:name=ZooKeeperExpiresPerSec,type=SessionExpireListener
kafka.server:name=ZooKeeperReadOnlyConnectsPerSec,type=SessionExpireListener
kafka.server:name=ZooKeeperSaslAuthenticationsPerSec,type=SessionExpireListener
kafka.server:name=ZooKeeperSyncConnectsPerSec,type=SessionExpireListener
kafka.server:networkProcessor=0,type=socket-server-metrics
kafka.server:networkProcessor=1,type=socket-server-metrics
kafka.server:networkProcessor=2,type=socket-server-metrics
kafka.server:networkProcessor=3,type=socket-server-metrics
kafka.server:networkProcessor=4,type=socket-server-metrics
kafka.server:networkProcessor=5,type=socket-server-metrics
kafka.server:networkProcessor=6,type=socket-server-metrics
kafka.server:networkProcessor=7,type=socket-server-metrics
kafka.server:networkProcessor=8,type=socket-server-metrics
kafka.server:networkProcessor=9,type=socket-server-metrics
kafka.server:type=Fetch
kafka.server:type=kafka-metrics-count
kafka.server:type=Produce

kafka:type=kafka.Log4jController
kafka.utils:name=cleaner-io,type=Throttler
org.apache.commons.pool2:name=pool2,type=GenericObjectPool
org.apache.commons.pool2:name=pool,type=GenericObjectPool

kafka.log:name=cleaner-recopy-percent,type=LogCleaner
kafka.log:name=max-buffer-utilization-percent,type=LogCleaner
kafka.log:name=max-clean-time-secs,type=LogCleaner
kafka.log:name=max-dirty-percent,type=LogCleanerManager
kafka.log:name=LogFlushRateAndTimeMs,type=LogFlushStats
kafka.log:name=LogEndOffset,partition=0,topic=qaastor-1.s8,type=Log
kafka.log:name=LogEndOffset,partition=1,topic=qaastor-1.s8,type=Log
kafka.log:name=LogEndOffset,partition=2,topic=qaastor-1.s8,type=Log
kafka.log:name=LogStartOffset,partition=0,topic=qaastor-1.s8,type=Log
kafka.log:name=LogStartOffset,partition=1,topic=qaastor-1.s8,type=Log
kafka.log:name=LogStartOffset,partition=2,topic=qaastor-1.s8,type=Log
kafka.log:name=NumLogSegments,partition=0,topic=qaastor-1.s8,type=Log
kafka.log:name=NumLogSegments,partition=1,topic=qaastor-1.s8,type=Log
kafka.log:name=NumLogSegments,partition=2,topic=qaastor-1.s8,type=Log
kafka.log:name=Size,partition=0,topic=qaastor-1.s8,type=Log
kafka.log:name=Size,partition=1,topic=qaastor-1.s8,type=Log
kafka.log:name=Size,partition=2,topic=qaastor-1.s8,type=Log
